# Generated by Django 3.1 on 2020-09-24 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='mass',
            new_name='mess',
        ),
    ]
