# Generated by Django 3.1 on 2020-09-28 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20200927_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='image',
            field=models.ImageField(default='p1.jpg', null=True, upload_to='profile_pics'),
        ),
    ]
